name: Validate with HACS

on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * *"

jobs:
  validate:
    runs-on: "self-hosted"
    name: Validate
    steps:
      - uses: "actions/checkout@v4"

      - name: HACS validation
        uses: "https://git.stebot76.noip.me/stephan/action@main"
        with:
          category: "plugin"
